### PR TITLE
Check errors, parse claims consistently and compare reuse

### PR DESCRIPTION
**Pull request by pascaldekloe**
Note the following errors in bench.txt.

```
--- FAIL: Benchmark_Two_ECDSA/check-ES256
    bench_test.go:231: jwt: token format is not valid
--- FAIL: Benchmark_Two_ECDSA/check-ES384
    bench_test.go:231: jwt: token format is not valid
```

### CODE REVIEW

**Comment by storozhukBM** [comment]
You have an error in your changes where you call bench without reuse `"sign-"+alg.String()+"-reuse"` and it changes the results.

Don't you consider this strange that after your changes to the benchmark, some methods started to work 2 times slower than before?

I'm sorry @pascaldekloe, but can you please double-check all the results?

Also @cristaloleg  and @pascaldekloe, I think in this project, we should embrace the fact that any raw numbers mean nothing without follow-up analysis. We should not post just numbers here, but also a detailed description of why certain methods and approaches are more performant or memory-efficient with profiler results, code snippets, etc. Such an approach will help us involve both libraries towards a better future, and it will act as a natural barrier for data misinterpretation and help to save the time of other contributors during the analysis. I'd add this requirement to README.

https://youtu.be/SKPdqgD1I2U?t=2838

**Comment by cristaloleg** [comment]
I made this repo just to collect benchmarks that I did, have something under one umbrella. That's not about "my func is faster than your func" at all. Will update readme to reduce a benchmark masturbation in the repo. Thank you for your comment.

**Comment by pascaldekloe** [comment]
Exactly @cristaloleg. Comparison validates your work, and sometimes you pick something up. I'm quite happy with the reuse idea. :-)

The number shift is because the current results skip parsing the (JSON) claims and such. This patch makes the comparison more fair/similar.

**Comment by cristaloleg** [comment]
```
--- FAIL: Benchmark_Two_ECDSA/check-ES256
    bench_test.go:231: jwt: token format is not valid
--- FAIL: Benchmark_Two_ECDSA/check-ES384
    bench_test.go:231: jwt: token format is not valid
```

cannot reproduce on v3.0.2

**Comment by pascaldekloe** [comment]
This is v3.0.2. Happens consistently too.

**Comment by cristaloleg** [comment]
Yep, I know it's v3.0.2, but it constantly works for me. Will ask you to run it from `master` once more if the problem occurs again - please add token to the output (check again that there is not other changes via `git status`)

**Comment by cristaloleg** [comment]
Hm, I see, you've changed bench and added `Parse` now it's a bit more clear, will check https://github.com/cristalhq/jwt/issues/42#issuecomment-668907468

**Comment by pascaldekloe** [comment]
```
% git diff bench_test.go 
diff --git a/jwt/bench_test.go b/jwt/bench_test.go
index a420945..96fd686 100644
--- a/jwt/bench_test.go
+++ b/jwt/bench_test.go
@@ -228,7 +228,7 @@ func Benchmark_Two_ECDSA(b *testing.B) {
                        for i := 0; i < b.N; i++ {
                                obj, err := jwt2.ParseAndVerify(token, verifier)
                                if err != nil {
-                                       b.Fatal(err)
+                                       b.Fatalf("%#x error: %s", token, err)
                                }
                                err = json.Unmarshal(obj.RawClaims(), new(map[string]interface{}))
                                if err != nil {
% go test -bench Two_ECDSA
goos: darwin
goarch: amd64
pkg: github.com/cristaloleg/benches/jwt
Benchmark_Two_ECDSA/sign-ES256-4         	   43089	     27947 ns/op
Benchmark_Two_ECDSA/sign-ES384-4         	     270	   4364781 ns/op
Benchmark_Two_ECDSA/sign-ES512-4         	     156	   7560259 ns/op
--- FAIL: Benchmark_Two_ECDSA/check-ES256
    bench_test.go:231: 0x65794a68624763694f694a46557a49314e694973496e523563434936496b705856434a392e65794a7063334d694f694a695a57356a61473168636d73694c434a70595851694f6a45314f5463794d5463314d5446392e635063455651695a416e42665a743458302d793672386671664e4e514b54792d3063375876777770364751596b3357474a555a454d41414359426f64766a3751427355763338497a626f53636f5573646d454d455a6700 error: jwt: token format is not valid
--- FAIL: Benchmark_Two_ECDSA/check-ES384
    bench_test.go:231: 0x65794a68624763694f694a46557a4d344e434973496e523563434936496b705856434a392e65794a7063334d694f694a695a57356a61473168636d73694c434a70595851694f6a45314f5463794d5463314d5446392e5164555156617861714a74663842584f6c4254434b635851594d4d6b5634747444785730794f51495f343030306b44586b442d7776734b6e456479703646626773657a6f4c7a5f304775576d5a5f5162796e577363525649596a6338537937742d76445a7971497659762d746b4a37413655326f395832546b4d6d596c5f41430000 error: jwt: token format is not valid
Benchmark_Two_ECDSA/check-ES512-4        	      80	  14838942 ns/op
--- FAIL: Benchmark_Two_ECDSA
FAIL
exit status 1
FAIL	github.com/cristaloleg/benches/jwt	6.527s
```

**Pull request closed without merging**
